export const {
    FB_API_KEY: API_KEY,
    FB_APP_ID: APP_ID,
    FB_AUTH_DOMAIN: AUTH_DOMAIN,
    FB_PROJECT_ID: PROJECT_ID,
    FB_STORAGE_BUCKET: STORAGE_BUCKET,
    FB_MESSAGING_SENDER_ID: MESSAGING_SENDER_ID,
    FB_MEASUREMENT_ID: MEASUREMENT_ID,
} = process.env;